### ISSUE TITLE
[Bug] Unable to run the docker-compose up 

### ISSUE THREAD

**Issue by Aju100** [r3curs1v3-pr0xy/vajra#24]
HI @r3curs1v3-pr0xy ,

Manual build version will work perfectly using installation guide of vajra and also node application should be run background on vps. It needs to be automate. We can use pm2 manager for running.

On the case of docker containerization, there is an issue of uncompatible version of docker-compose .
I have tested on AWS Ec2 instance, please have a look of the output. Also I tried on my ubuntu machine.
![dock](https://user-images.githubusercontent.com/29862610/115324899-6a029b00-a1aa-11eb-85f8-2cd1be83822a.png)

Also I have updated and upgraded docker and docker-compose. The docker-compose.yml format is in 3.8 and the version which is need to be compatible is also documented. Still it's not supported. Take a look of documentation.
![do](https://user-images.githubusercontent.com/29862610/115324929-7981e400-a1aa-11eb-9957-c9019169bad4.png)
[Reference](https://docs.docker.com/compose/compose-file/)

Solution: update the docker-compose.yml of version to 3 and it works perfectly fine. 
```
version: "3"

services:
  vajra:
    container_name: vajras
    restart: always
    working_dir: /app
    #volumes:
     # - ./:/app
    ports:
      - "${PORT}:80"
      ........
```

I am looking forward to hear from you about this issue. Thanks

Regards,
Aju Tamang
